FROM golang:1.19 as build
WORKDIR /build
COPY go.mod go.sum ./
RUN \
  --mount=type=cache,target=/go \
  go mod download
COPY . .
RUN \
  --mount=type=cache,target=/root/.cache/go-build \
  --mount=type=cache,target=/go \
  CGO_ENABLED=0 go build

FROM debian:11-slim
COPY --from=build /build/large /usr/local/bin/large
