build:
	docker build -t registry.sikahq.com/pseudo-private/hello-world .

push:
	docker push registry.sikahq.com/pseudo-private/hello-world

run:
	docker run -p 80:80 registry.sikahq.com/pseudo-private/hello-world
