version: "3.7"
services:
  web:
    image: nginx
    ports:
      - ${PORT:-80}:80
    configs:
      - source: index
        target: /usr/share/nginx/html/index.html

configs:
  index:
    file: ./index.html
