version: "3.8"
services:
  counter:
    build: .
    image: ttl.sh/dte/external-traefik/counter
    depends_on:
      - redis
    labels:
      traefik.enable: true
      traefik.frontend.rule: Host:127.0.0.1
      traefik.docker.network: traefik
    networks:
      - traefik
      - backend
  redis:
    image: redis
    networks:
      - backend
networks:
  backend:
    internal: true
  traefik:
    external:
      name: traefik
