FROM debian:13-slim
RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3=3.13.5-1 \
        python3-pip=25.1.1+dfsg-1 && \
    rm -rf /var/lib/apt/lists
WORKDIR /app
COPY requirements.txt .
RUN \
  pip3 install \
    --break-system-packages \
    --no-cache-dir \
    -r requirements.txt
COPY . .
CMD ["python3", "app.py"]
EXPOSE 80
