version: "3.8"
name: counter
services:
  counter:
    build: .
    image: reg.istry.cz/dte/multiple-composes/counter
    depends_on:
      - redis
    labels:
      traefik.enable: "true"
      traefik.http.routers.counter.rule: Host(`127.0.0.1`)
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
