up:
	docker compose up -d --remove-orphans

down:
	docker compose down --remove-orphans

run-test:
	docker compose run test

use-ports:
	cp .env.ports .env

use-test:
	cp .env.test .env

use-traefik:
	cp .env.traefik .env

use-traefik-external:
	cp .env.traefik-external .env
