services:
  tests:
    build: ./tests
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - backend
      - frontend
