FROM eclipse-temurin:21-jdk AS build
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends maven && \
  rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY pom.xml .
COPY src/ src/
RUN mvn package -q -DskipTests
CMD ["java", "-jar", "/app/target/springboot-example-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
