FROM eclipse-temurin:21-jdk AS build
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends maven && \
  rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY pom.xml .
COPY src/ src/
RUN mvn package -q -DskipTests

FROM gcr.io/distroless/java21-debian13
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
CMD ["app.jar"]
EXPOSE 8080
